dogsite/dogs/urls.py
from django.conf.urls import patterns, url
from dogs import views

urlpatterns = patterns('',
    url(r'^dog/create/', views.DogCreateView.as_view(), name='dog-create'),
    url(r'^$', views.index, name='index'),
    url(r'^dog/success/(?P<dog>\w+)/$', views.success, name='dog-success'),
    url(r'^dog/all', views.DogListView.as_view(), name='dog-list'),
    url(r'^dog/(?P<pk>\d+)/$', views.DogDetailView.as_view(), name='dog-detail'),
    url(r'^search-form/$', views.search_form, name="search-form"),
    url(r'^search/$', views.search, name="search"),
)

dogsite/dogsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dogsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'^', include('dogs.urls', namespace="dogs")),
)

dogsite/dogs/models.py
from django.db import models


class Dog(models.Model):
    name = models.CharField(max_length=50, verbose_name=u"Dog's Name")
    owner = models.CharField(max_length=50, verbose_name=u"Owner's Name")
    photo = models.ImageField(upload_to='dogs', verbose_name=u"Photo of Dog")

    def __unicode__(self):
        return u'%s' % self.name

dogsite/dogs/forms.py
from django import forms

dogsite/dogs/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, CreateView
from dogs.models import Dog


class DogCreateView(CreateView):
    template_name = 'dogs/dog_create.html'
    model = Dog
    fields = ['name', 'owner', 'photo']

    def get_success_url(self):
        return reverse('dogs:dog-success', kwargs={"dog": self.object.pk})


class DogListView(ListView):
    template_name = 'dog_list.html'
    model = Dog


class DogDetailView(DetailView):
    template_name = 'dogs/dog_detail.html'
    model = Dog


def index(request):
    object_list = Dog.objects.all()
    return render(request, 'dogs/index.html', {'object_list': object_list})


def success(request, dog=None):
    dog_object = Dog.objects.get(pk=dog)
    return render(request, 'dogs/success.html', {'dog': dog_object})


def search_form(request):
    return render(request, 'dogs/search_form.html')


def search(request):
    if 'q' in request.GET:
        q = request.GET['q']
        if q:
            dog_names = Dog.objects.filter(name__icontains=q)
            owner_names = Dog.objects.filter(owner__icontains=q)
        else:
            dog_names = None
            owner_names = None
        return render(request, 'dogs/search.html', {'dog_names': dog_names,
                                                    'owner_names': owner_names,
                                                    'query': q})
    else:
        message = 'Please submit a search term'
        return render(request, 'dogs/search_form', {'message': message})

    return render(request, 'dogs/search.html')

dogsite/dogs/templates/dogs/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dog Database</title>
    <link rel="shortcut icon" href="{% static 'images/paw.png' %}">

    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>

  </head>
  <body>
    <nav class="navbar">
      <ul>
        <li>
          <a class="navbar-brand" href="{% url 'dogs:index' %}"><img src="{% static 'images/paw.png' %}" width="30px" height="30px"></a>
        </li>
        <li class="navbar-right">
          <form class="navbar-form" role="search" action="{% url 'dogs:search' %}" method="get">
            <input type="text" name="q" placeholder="Search">
            <input type="submit" value="Submit">
          </form>
        </li>
      </ul>
    </nav>
    {% block content %}
    {% endblock %}

    <script src="{% static 'js/lightbox.js' %}"></script>
  </body>
</html>

dogsite/dogs/templates/dogs/dog_create.html
<div class="create-form">
<form action="{% url 'dogs:dog-create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>
</div>

dogsite/dogs/templates/dogs/dog_detail.html
<div class='dog-detail'>
    <div><img src="{{ dog.photo.url }}" class="lightbox-image"></div>
    <div><b>Dog</b>: {{ dog.name }}</div>
    <div><b>Owner</b>: {{ dog.owner }}</div>
</div>

dogsite/dogs/templates/dogs/dog_list.html
<div class="grid">
    <div class="col-2-3">
        <div class='dog-box' onclick="javascript:lightbox(null, '{% url 'dogs:dog-create' %}');">
            <div class='add-dog'>+ add your dog</div>
        </div>
        {% for dog in object_list %}
        <div class='dog-box' onclick="javascript:lightbox(null, '{% url 'dogs:dog-detail' pk=dog.pk %}');">
            <div class='box-thumb'><img src="{{ dog.photo.url }}" class="thumbnail"></div>
            <div class='box-details'><b>{{ dog.name }}</b> - {{ dog.owner }}</a></div>
        </div>
        {% endfor %}
    </div>
</div>

dogsite/dogs/templates/dogs/index.html
{% extends "dogs/base.html" %}

{% block content %}
<center>
<h1>Welcome to the Dog Database</h1>
<p>Scroll to view dogs or <a href="javascript:lightbox(null, '{% url 'dogs:dog-create' %}');">add your own</a>.</p>
<p>Use the search tool above to find a dog by its name or owner.</p>

{% include 'dogs/dog_list.html' %}

{% endblock %}

dogsite/dogs/templates/dogs/search.html
{% extends "dogs/base.html" %}

{% block content %}
<center>
{% if dog_names %}
<h1>Dogs matching <i>{{query}}</i></h1>
<div class="grid">
    <div class="col-2-3">
        {% for dog in dog_names %}
        <div class='dog-box' onclick="javascript:lightbox(null, '{% url 'dogs:dog-detail' pk=dog.pk %}');">
            <div class='box-thumb'><img src="{{ dog.photo.url }}" class="thumbnail"></div>
            <div class='box-details'><b>{{ dog.name }}</b> - {{ dog.owner }}</a></div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

{% if owner_names %}
<h1>Owners matching <i>{{query}}</i></h1>
<div class="grid">
    <div class="col-2-3">
        {% for dog in owner_names %}
        <div class='dog-box' onclick="javascript:lightbox(null, '{% url 'dogs:dog-detail' pk=dog.pk %}');">
            <div class='box-thumb'><img src="{{ dog.photo.url }}" class="thumbnail"></div>
            <div class='box-details'><b>{{ dog.name }}</b> - {{ dog.owner }}</a></div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

{% if not dog_names and not owner_names %}
<p>No results matching your query</p>
{% endif %}
</center>
{% endblock %}

dogsite/dogs/templates/dogs/search_form.html
{% extends "dogs/base.html" %}

{% block content %}
{{ message }}
<form action="{% url 'dogs:search' %}" method="get">
    <input type="text" name="q">
    <input type="submit" value="Search">
</form>
{% endblock %}

dogsite/dogs/templates/dogs/success.html
{% extends "dogs/base.html" %}

{% block content %}
<center>

    <h2>Your dog has been created!</h2>
    <div><img src="{{ dog.photo.url }}" class="lightbox-image"></div>
    <div><b>Dog</b>: {{ dog.name }}</div>
    <div><b>Owner</b>: {{ dog.owner }}</div>
    <p><a href="{% url 'dogs:index' %}">Return Home</a>
{% endblock %}